FROM node:20-alpine

WORKDIR /workspace/backend

COPY backend/package.json backend/package-lock.json ./
RUN npm ci

COPY backend ./
COPY shared ../shared

EXPOSE 3000
EXPOSE 9229

CMD ["npm", "run", "dev"]
