const GERMAN_TEXT_REPLACEMENTS: ReadonlyArray<readonly [RegExp, string]> = [
  [/\bSchmerzstaerke\b/g, 'Schmerzstärke'],
  [/\bschmerzstaerke\b/g, 'schmerzstärke'],
  [/\bBeschwerdestaerke\b/g, 'Beschwerdestärke'],
  [/\bbeschwerdestaerke\b/g, 'beschwerdestärke'],
  [/\bBeschwerdegefuehl\b/g, 'Beschwerdegefühl'],
  [/\bbeschwerdegefuehl\b/g, 'beschwerdegefühl'],
  [/\bAerzt/g, 'Ärzt'],
  [/\baerzt/g, 'ärzt'],
  [/\bFachaerzt/g, 'Fachärzt'],
  [/\bfachaerzt/g, 'fachärzt'],
  [/\bHausaerzt/g, 'Hausärzt'],
  [/\bhausaerzt/g, 'hausärzt'],
  [/\bAbklaer/g, 'Abklär'],
  [/\babklaer/g, 'abklär'],
  [/\bKoennen\b/g, 'Können'],
  [/\bkoennen\b/g, 'können'],
  [/\bZunaechst\b/g, 'Zunächst'],
  [/\bzunaechst\b/g, 'zunächst'],
  [/\bFuer\b/g, 'Für'],
  [/\bfuer\b/g, 'für'],
  [/\bMoeglich\b/g, 'Möglich'],
  [/\bmoeglich\b/g, 'möglich'],
  [/\bGroesse\b/g, 'Größe'],
  [/\bgroesse\b/g, 'größe'],
  [/\bGrosse\b/g, 'Größe'],
  [/\bgrosse\b/g, 'große'],
  [/\bVerfuegbar\b/g, 'Verfügbar'],
  [/\bverfuegbar\b/g, 'verfügbar'],
  [/\bUebergebenen\b/g, 'Übergebenen'],
  [/\buebergebenen\b/g, 'übergebenen'],
  [/\bEnthaelt\b/g, 'Enthält'],
  [/\benthaelt\b/g, 'enthält'],
  [/\bAusgewaehlte\b/g, 'Ausgewählte'],
  [/\bausgewaehlte\b/g, 'ausgewählte'],
  [/\bAusgewaehlt\b/g, 'Ausgewählt'],
  [/\bausgewaehlt\b/g, 'ausgewählt'],
  [/\bBegruendung\b/g, 'Begründung'],
  [/\bbegruendung\b/g, 'begründung'],
  [/\bSchilddruesenunterfunktion\b/g, 'Schilddrüsenunterfunktion'],
  [/\bschilddruesenunterfunktion\b/g, 'schilddrüsenunterfunktion'],
]

export function normalizeGermanText(value: string): string {
  return GERMAN_TEXT_REPLACEMENTS.reduce(
    (normalizedValue, [pattern, replacement]) => normalizedValue.replace(pattern, replacement),
    value,
  )
}
